server:
  port: 8888
spring:
  datasource:  # 这里配置的quartz框架不生效，需要使用下面quartz自己的数据库配置
    url: jdbc:mysql://10.254.7.226:3306/quartz_jobs?useUnicode=true&useSSL=false
    username: root
    password: cloudos
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: myDS
          dataSource:
            myDS:
              driver: com.mysql.jdbc.Driver
              URL: jdbc:mysql://10.254.7.226:3306/quartz_jobs?useUnicode=true&useSSL=false
              user: root
              password: cloudos
              maxConnections: 5
              validationQuery: select 0
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    